//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMMPlugin.i18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DMM {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DMM() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMMPlugin.i18n.DMM", typeof(DMM).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Account 的本地化字符串。
        /// </summary>
        internal static string I18N_AccountEdit_Account {
            get {
                return ResourceManager.GetString("I18N_AccountEdit_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string I18N_AccountEdit_Delete {
            get {
                return ResourceManager.GetString("I18N_AccountEdit_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter DMM Account (Email) 的本地化字符串。
        /// </summary>
        internal static string I18N_AccountEdit_EnterAccount {
            get {
                return ResourceManager.GetString("I18N_AccountEdit_EnterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter Name 的本地化字符串。
        /// </summary>
        internal static string I18N_AccountEdit_EnterName {
            get {
                return ResourceManager.GetString("I18N_AccountEdit_EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter DMM Password 的本地化字符串。
        /// </summary>
        internal static string I18N_AccountEdit_EnterPassword {
            get {
                return ResourceManager.GetString("I18N_AccountEdit_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string I18N_AccountEdit_Name {
            get {
                return ResourceManager.GetString("I18N_AccountEdit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name already exists 的本地化字符串。
        /// </summary>
        internal static string I18N_AccountEdit_NameDuplicate {
            get {
                return ResourceManager.GetString("I18N_AccountEdit_NameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not set 的本地化字符串。
        /// </summary>
        internal static string I18N_AccountEdit_NameNotSet {
            get {
                return ResourceManager.GetString("I18N_AccountEdit_NameNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string I18N_AccountEdit_Password {
            get {
                return ResourceManager.GetString("I18N_AccountEdit_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ******** 的本地化字符串。
        /// </summary>
        internal static string I18N_AccountEdit_PasswordHidden {
            get {
                return ResourceManager.GetString("I18N_AccountEdit_PasswordHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid/Expired 的本地化字符串。
        /// </summary>
        internal static string I18N_AccountEdit_TokenInvalid {
            get {
                return ResourceManager.GetString("I18N_AccountEdit_TokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Token Status 的本地化字符串。
        /// </summary>
        internal static string I18N_AccountEdit_TokenStatus {
            get {
                return ResourceManager.GetString("I18N_AccountEdit_TokenStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Valid (Expires: {0:yyyy-MM-dd HH:mm:ss}) 的本地化字符串。
        /// </summary>
        internal static string I18N_AccountEdit_TokenValid {
            get {
                return ResourceManager.GetString("I18N_AccountEdit_TokenValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add account 的本地化字符串。
        /// </summary>
        internal static string I18N_AddAccount {
            get {
                return ResourceManager.GetString("I18N_AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client launch cancelled 的本地化字符串。
        /// </summary>
        internal static string I18N_AppLaunchCanceled {
            get {
                return ResourceManager.GetString("I18N_AppLaunchCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incorrect game path? 的本地化字符串。
        /// </summary>
        internal static string I18N_AppRootPathNull {
            get {
                return ResourceManager.GetString("I18N_AppRootPathNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to get access token: {0} 的本地化字符串。
        /// </summary>
        internal static string I18N_Auth_AccessTokenFailed {
            get {
                return ResourceManager.GetString("I18N_Auth_AccessTokenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to get OAuth code 的本地化字符串。
        /// </summary>
        internal static string I18N_Auth_OAuthCodeNotFound {
            get {
                return ResourceManager.GetString("I18N_Auth_OAuthCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to get OAuth redirect URL, please check if account and password are correct 的本地化字符串。
        /// </summary>
        internal static string I18N_Auth_OAuthUrlNotFound {
            get {
                return ResourceManager.GetString("I18N_Auth_OAuthUrlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to get OAuth redirect URL 的本地化字符串。
        /// </summary>
        internal static string I18N_Auth_RedirectUrlNotFound {
            get {
                return ResourceManager.GetString("I18N_Auth_RedirectUrlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to agree to terms: {0} 的本地化字符串。
        /// </summary>
        internal static string I18N_Auth_TermsAgreeFailed {
            get {
                return ResourceManager.GetString("I18N_Auth_TermsAgreeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to get login form token 的本地化字符串。
        /// </summary>
        internal static string I18N_Auth_TokenNotFound {
            get {
                return ResourceManager.GetString("I18N_Auth_TokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        internal static string I18N_Back {
            get {
                return ResourceManager.GetString("I18N_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string I18N_Cancel {
            get {
                return ResourceManager.GetString("I18N_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press Enter on the selected account to delete 的本地化字符串。
        /// </summary>
        internal static string I18N_DeleteAccountInstruction {
            get {
                return ResourceManager.GetString("I18N_DeleteAccountInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DMM Session has expired 的本地化字符串。
        /// </summary>
        internal static string I18N_DMMTokenExpired {
            get {
                return ResourceManager.GetString("I18N_DMMTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a note for this account: 的本地化字符串。
        /// </summary>
        internal static string I18N_InputAccountCommentPrompt {
            get {
                return ResourceManager.GetString("I18N_InputAccountCommentPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter actauth: 的本地化字符串。
        /// </summary>
        internal static string I18N_InputActauthPrompt {
            get {
                return ResourceManager.GetString("I18N_InputActauthPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter hdd_serial (current value: {0}, leave blank to not modify): 的本地化字符串。
        /// </summary>
        internal static string I18N_InputHddSerialPrompt {
            get {
                return ResourceManager.GetString("I18N_InputHddSerialPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter mac_address (current value: {0}, leave blank to not modify): 的本地化字符串。
        /// </summary>
        internal static string I18N_InputMacAddressPrompt {
            get {
                return ResourceManager.GetString("I18N_InputMacAddressPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter motherboard (current value: {0}, leave blank to not modify): 的本地化字符串。
        /// </summary>
        internal static string I18N_InputMotherboardPrompt {
            get {
                return ResourceManager.GetString("I18N_InputMotherboardPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter savedata_file_path (leave blank to use default): 的本地化字符串。
        /// </summary>
        internal static string I18N_InputSaveDataFilePathPrompt {
            get {
                return ResourceManager.GetString("I18N_InputSaveDataFilePathPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter umamusume_file_path (current value: {0}, leave blank to not modify): 的本地化字符串。
        /// </summary>
        internal static string I18N_InputUmamusumeFilePathPrompt {
            get {
                return ResourceManager.GetString("I18N_InputUmamusumeFilePathPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter user_os (current value: {0}, leave blank to not modify): 的本地化字符串。
        /// </summary>
        internal static string I18N_InputUserOsPrompt {
            get {
                return ResourceManager.GetString("I18N_InputUserOsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch failed: {0} 的本地化字符串。
        /// </summary>
        internal static string I18N_Launch_Failed {
            get {
                return ResourceManager.GetString("I18N_Launch_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save data processing failed 的本地化字符串。
        /// </summary>
        internal static string I18N_Launch_SaveDataFailed {
            get {
                return ResourceManager.GetString("I18N_Launch_SaveDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple accounts found, please choose which one to start 的本地化字符串。
        /// </summary>
        internal static string I18N_MultipleAccountsFound {
            get {
                return ResourceManager.GetString("I18N_MultipleAccountsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is this the account you logged into last time? If yes, the current SaveData.db will be linked to this account. If no, SaveData.db will be renamed to SaveData.db.old. 的本地化字符串。
        /// </summary>
        internal static string I18N_SaveData_AskIsLastLoginAccount {
            get {
                return ResourceManager.GetString("I18N_SaveData_AskIsLastLoginAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save data has been associated with account [{0}] 的本地化字符串。
        /// </summary>
        internal static string I18N_SaveData_Associated {
            get {
                return ResourceManager.GetString("I18N_SaveData_Associated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to associate save data: {0} 的本地化字符串。
        /// </summary>
        internal static string I18N_SaveData_AssociateFailed {
            get {
                return ResourceManager.GetString("I18N_SaveData_AssociateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup created 的本地化字符串。
        /// </summary>
        internal static string I18N_SaveData_BackupCreated {
            get {
                return ResourceManager.GetString("I18N_SaveData_BackupCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaded save data for account [{0}] 的本地化字符串。
        /// </summary>
        internal static string I18N_SaveData_Loaded {
            get {
                return ResourceManager.GetString("I18N_SaveData_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load save data: {0} 的本地化字符串。
        /// </summary>
        internal static string I18N_SaveData_LoadFailed {
            get {
                return ResourceManager.GetString("I18N_SaveData_LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account save data does not exist, a new archive will be created: {0} 的本地化字符串。
        /// </summary>
        internal static string I18N_SaveData_NewArchiveWillBeCreated {
            get {
                return ResourceManager.GetString("I18N_SaveData_NewArchiveWillBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot determine save data path 的本地化字符串。
        /// </summary>
        internal static string I18N_SaveData_PathNotDetermined {
            get {
                return ResourceManager.GetString("I18N_SaveData_PathNotDetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SaveData.db has been renamed to {0} 的本地化字符串。
        /// </summary>
        internal static string I18N_SaveData_RenamedToOld {
            get {
                return ResourceManager.GetString("I18N_SaveData_RenamedToOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to rename save data: {0} 的本地化字符串。
        /// </summary>
        internal static string I18N_SaveData_RenameFailed {
            get {
                return ResourceManager.GetString("I18N_SaveData_RenameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Same account, skipping save data switching 的本地化字符串。
        /// </summary>
        internal static string I18N_SaveData_SameAccountSkip {
            get {
                return ResourceManager.GetString("I18N_SaveData_SameAccountSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save data saved for account [{0}] 的本地化字符串。
        /// </summary>
        internal static string I18N_SaveData_SavedForAccount {
            get {
                return ResourceManager.GetString("I18N_SaveData_SavedForAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to save save data: {0} 的本地化字符串。
        /// </summary>
        internal static string I18N_SaveData_SaveFailed {
            get {
                return ResourceManager.GetString("I18N_SaveData_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Using default save data 的本地化字符串。
        /// </summary>
        internal static string I18N_SaveData_UsingDefault {
            get {
                return ResourceManager.GetString("I18N_SaveData_UsingDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [yellow]Detecting if umamusume.exe is running[/] 的本地化字符串。
        /// </summary>
        internal static string I18N_Start_Checking {
            get {
                return ResourceManager.GetString("I18N_Start_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected umamusume.exe is running, directly starting the server 的本地化字符串。
        /// </summary>
        internal static string I18N_Start_Checking_AlreadyRunning {
            get {
                return ResourceManager.GetString("I18N_Start_Checking_AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected {0} instances of umamusume.exe running 的本地化字符串。
        /// </summary>
        internal static string I18N_Start_Checking_Found {
            get {
                return ResourceManager.GetString("I18N_Start_Checking_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [grey]Log: [/] {0} 的本地化字符串。
        /// </summary>
        internal static string I18N_Start_Checking_Log {
            get {
                return ResourceManager.GetString("I18N_Start_Checking_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [bold blue]Acquiring DMM One-time Token[/] 的本地化字符串。
        /// </summary>
        internal static string I18N_Start_GetToken {
            get {
                return ResourceManager.GetString("I18N_Start_GetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starting umamusume.exe 的本地化字符串。
        /// </summary>
        internal static string I18N_Start_Launching {
            get {
                return ResourceManager.GetString("I18N_Start_Launching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [bold green]Launched[/] 的本地化字符串。
        /// </summary>
        internal static string I18N_Start_Started {
            get {
                return ResourceManager.GetString("I18N_Start_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to acquire DMM One-time Token 的本地化字符串。
        /// </summary>
        internal static string I18N_Start_TokenFailed {
            get {
                return ResourceManager.GetString("I18N_Start_TokenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DMM One-time Token acquired 的本地化字符串。
        /// </summary>
        internal static string I18N_Start_TokenGot {
            get {
                return ResourceManager.GetString("I18N_Start_TokenGot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to agree to game terms, please use DMM Game Player to agree manually 的本地化字符串。
        /// </summary>
        internal static string I18N_Terms_AgreeFailed {
            get {
                return ResourceManager.GetString("I18N_Terms_AgreeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game terms agreement required, auto-agreeing... 的本地化字符串。
        /// </summary>
        internal static string I18N_Terms_Required {
            get {
                return ResourceManager.GetString("I18N_Terms_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot get valid access token 的本地化字符串。
        /// </summary>
        internal static string I18N_Token_CannotGetValid {
            get {
                return ResourceManager.GetString("I18N_Token_CannotGetValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Token has expired, but account or password is not set, cannot auto re-authenticate 的本地化字符串。
        /// </summary>
        internal static string I18N_Token_ExpiredNoCredentials {
            get {
                return ResourceManager.GetString("I18N_Token_ExpiredNoCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Re-authentication failed 的本地化字符串。
        /// </summary>
        internal static string I18N_Token_ReauthFailed {
            get {
                return ResourceManager.GetString("I18N_Token_ReauthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Re-authentication failed: {0} 的本地化字符串。
        /// </summary>
        internal static string I18N_Token_RefreshFailed {
            get {
                return ResourceManager.GetString("I18N_Token_RefreshFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Token has expired, re-authenticating with account {0}... 的本地化字符串。
        /// </summary>
        internal static string I18N_Token_Refreshing {
            get {
                return ResourceManager.GetString("I18N_Token_Refreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Token re-acquired successfully, expires at: {0:yyyy-MM-dd HH:mm:ss} 的本地化字符串。
        /// </summary>
        internal static string I18N_Token_RefreshSuccess {
            get {
                return ResourceManager.GetString("I18N_Token_RefreshSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attempting re-authentication... 的本地化字符串。
        /// </summary>
        internal static string I18N_Token_RetryAuth {
            get {
                return ResourceManager.GetString("I18N_Token_RetryAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid/Expired 的本地化字符串。
        /// </summary>
        internal static string I18N_TokenStatus_Invalid {
            get {
                return ResourceManager.GetString("I18N_TokenStatus_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Valid 的本地化字符串。
        /// </summary>
        internal static string I18N_TokenStatus_Valid {
            get {
                return ResourceManager.GetString("I18N_TokenStatus_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown .token key {0} 的本地化字符串。
        /// </summary>
        internal static string I18N_UnknownTokenKey {
            get {
                return ResourceManager.GetString("I18N_UnknownTokenKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return 的本地化字符串。
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This feature requires an environment that can access DMM/Umamusume without a proxy (in Japan/has global proxy, etc., excluding accelerators as they don&apos;t accelerate URA itself).
        ///This feature is only suitable for those who don&apos;t like launching DMM every time or hate frequent DMM updates, but DMMGamePlayer still needs to be installed and is responsible for updates.
        ///Do you want to enable this feature? 的本地化字符串。
        /// </summary>
        internal static string Tabs_DMM_Caution {
            get {
                return ResourceManager.GetString("Tabs_DMM_Caution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Accounts 的本地化字符串。
        /// </summary>
        internal static string Tabs_DMM_EditAccounts {
            get {
                return ResourceManager.GetString("Tabs_DMM_EditAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string Tabs_DMM_EditAccounts_Add {
            get {
                return ResourceManager.GetString("Tabs_DMM_EditAccounts_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Tabs_DMM_EditAccounts_Delete {
            get {
                return ResourceManager.GetString("Tabs_DMM_EditAccounts_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input Name 的本地化字符串。
        /// </summary>
        internal static string Tabs_DMM_EditAccounts_InputName {
            get {
                return ResourceManager.GetString("Tabs_DMM_EditAccounts_InputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name already exists 的本地化字符串。
        /// </summary>
        internal static string Tabs_DMM_EditAccounts_InputName_Duplicate {
            get {
                return ResourceManager.GetString("Tabs_DMM_EditAccounts_InputName_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input SaveData Path (can be empty) 的本地化字符串。
        /// </summary>
        internal static string Tabs_DMM_EditAccounts_InputSavePath {
            get {
                return ResourceManager.GetString("Tabs_DMM_EditAccounts_InputSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string Tabs_DMM_EditAccounts_Name {
            get {
                return ResourceManager.GetString("Tabs_DMM_EditAccounts_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SaveData Path 的本地化字符串。
        /// </summary>
        internal static string Tabs_DMM_EditAccounts_SavePath {
            get {
                return ResourceManager.GetString("Tabs_DMM_EditAccounts_SavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Machine Information 的本地化字符串。
        /// </summary>
        internal static string Tabs_DMM_EditMachineInformation {
            get {
                return ResourceManager.GetString("Tabs_DMM_EditMachineInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input hdd_serial 的本地化字符串。
        /// </summary>
        internal static string Tabs_DMM_EditMachineInformation_InputHS {
            get {
                return ResourceManager.GetString("Tabs_DMM_EditMachineInformation_InputHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input mac_address 的本地化字符串。
        /// </summary>
        internal static string Tabs_DMM_EditMachineInformation_InputMA {
            get {
                return ResourceManager.GetString("Tabs_DMM_EditMachineInformation_InputMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input motherboard 的本地化字符串。
        /// </summary>
        internal static string Tabs_DMM_EditMachineInformation_InputMB {
            get {
                return ResourceManager.GetString("Tabs_DMM_EditMachineInformation_InputMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input user_os 的本地化字符串。
        /// </summary>
        internal static string Tabs_DMM_EditMachineInformation_InputOS {
            get {
                return ResourceManager.GetString("Tabs_DMM_EditMachineInformation_InputOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input Umamusume Path 的本地化字符串。
        /// </summary>
        internal static string Tabs_DMM_EditMachineInformation_InputUmamusumePath {
            get {
                return ResourceManager.GetString("Tabs_DMM_EditMachineInformation_InputUmamusumePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable 的本地化字符串。
        /// </summary>
        internal static string Tabs_DMM_Enable {
            get {
                return ResourceManager.GetString("Tabs_DMM_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DMM 的本地化字符串。
        /// </summary>
        internal static string Tabs_DMM_Title {
            get {
                return ResourceManager.GetString("Tabs_DMM_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View DMMGamePlayer Info 的本地化字符串。
        /// </summary>
        internal static string Tabs_DMM_ViewLauncherInformation {
            get {
                return ResourceManager.GetString("Tabs_DMM_ViewLauncherInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modification not supported, please edit config.yaml directly. Press Enter to return. 的本地化字符串。
        /// </summary>
        internal static string Tabs_DMM_ViewLauncherInformation_Caution {
            get {
                return ResourceManager.GetString("Tabs_DMM_ViewLauncherInformation_Caution", resourceCulture);
            }
        }
    }
}
